-- AlterTable
ALTER TABLE `Pelaku_wisata` ADD COLUMN `Deskripsi_wisata` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `alamat` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `email` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `fasilitas` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `nama_wisata` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `no_telpon` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `tarif` DOUBLE NOT NULL DEFAULT 0.0;
